version: "3"

services:
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
      #args:
    ports:
      - "8090:80"
    volumes:
      - ./site/:/www:rw
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log/:/var/log/nginx/:rw
    depends_on:
      - php
    networks:
      - frontend
  php:
    build: ./php/php72/
    expose:
      - "9000"
    volumes:
      - ./site/:/www:rw
      - ./php/php72/conf/php/:/usr/local/etc/php/
      - ./php/php72/conf/php-fpm.d/:/usr/local/etc/php-fpm.d/:rw
      - ./php/php72/log/php-fpm/:/var/log/:rw
    depends_on:
      - mysql
      - redis
      - mongo
    networks:
      - frontend
      - backend

  mysql:
    build: ./mysql/
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf/:/etc/mysql/:rw
      - ./mysql/data/:/var/lib/mysql/:rw
      - ./mysql/log/:/var/log/mysql/:rw
    env_file: ./mysql/env_config.env
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: "renyimin"
    networks:
      - backend

  mongo:
      build: ./mongo/
      ports:
        - 27018:27017
      volumes:
        - ./mongo/data:/data:rw
        - ./mongo/data:/var/log/mongodb/:rw

  redis:
    build: ./redis/
    volumes:
      - ./redis/conf/:/usr/local/etc/redis
      - ./redis/data/:/data:rw
      - ./redis/log/:/var/log/
    ports:
      - "6380:6379"

networks:
    frontend:
    backend: